### ISSUE TITLE
更换gocq协议后重新部署yunzai私聊和群消息无响应

### ISSUE THREAD

**Issue by subwaymui** [TimeRainStarSky/Yunzai#68]
![QQ图片20240125172012](https://github.com/TimeRainStarSky/Yunzai/assets/67714528/ab6a92fc-acda-49cf-8dc4-e2452e218af2)

协议版本：qocq v1.2 QQ版本号8.9.96+Qsign8.9.96

如图红色框在qq发送消息或设置主人无响应，但是黄色框在服务器控制台发送帮助或设置主人有对应响应，是不是应该考虑是协议版本的问题？

**Comment by TimeRainStarSky** [comment]
下载运行 [go-cqhttp](https://docs.go-cqhttp.org)，选择反向 WebSocket，修改 `config.yml`，以下为必改项：

```yaml
uin: 账号
password: '密码'
post-format: array
universal: ws://localhost:2536/go-cqhttp
```
